[package]
name = "poc-framework"
version = "0.1.4"
authors = []
edition = "2018"
repository = "https://github.com/neodyme-labs/solana-poc-framework"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["solana", "smart", "contracts"]
description = "A framework for creating PoC's for Solana Smart Contracts in a painless and intuitive way"

[dependencies]
itertools = "0.10.1"
bincode = "1.3.3"
rand = "0.7.3"
tempfile = "3.2.0"
borsh = "0.9.1"
solana-sdk = "=1.8.14"
solana-program = "=1.8.14"
solana-logger = "=1.8.14"
solana-runtime = "=1.8.14"
solana-transaction-status = "=1.8.14"
solana-cli-output = "=1.8.14"
solana-bpf-loader-program = "=1.8.14"
solana-ed25519-program = "=1.8.14"
solana-compute-budget-program = "=1.8.14"
solana-vote-program = "=1.8.14"
solana-stake-program = "=1.8.14"
solana-config-program = "=1.8.14"
solana-secp256k1-program = "=1.8.14"
solana-client = "=1.8.14"
solana-faucet = "=1.8.14"
spl-token = "3.2.0"
spl-memo = "3.0.1"
spl-associated-token-account = "1.0.3"
serde = "1.0.125"
sha2 = "0.9.5"
libsecp256k1 = "0.7.0"
sha3 = "0.10.0"
hex = "0.4.3"
once_cell = "1.9.0"
